### ISSUE TITLE
Optimisation du plugin

### ISSUE THREAD

**Issue by ek0onsec** [Charpyy/OpenWar-ClearLag#1]
Salut !  @Charpyy 
J'ai lu en diagonale ton code et je te propose une version un peu plus optimisée. 
Après, à toi de voir si tu prends ou non ces optimisations en compte.

Je te colle le code optimisé en brut comme ça et j'explique ensuite.

```java
package com.openwar.openwarclearlag;

import net.md_5.bungee.api.ChatMessageType;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Item;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitRunnable;

import java.util.HashSet;
import java.util.Set;

public final class Main extends JavaPlugin {
    private static final String LOGO = "§8» §cOpenWar §f- §cLag §8« §f";
    private static final Set<Material> ITEMS_TO_CLEAR = new HashSet<>();

    @Override
    public void onEnable() {
        initItemsToClear();
        scheduleClearTask();
    }

    private void initItemsToClear() {
        ITEMS_TO_CLEAR.add(Material.matchMaterial("hbm:sulfur")),
        ITEMS_TO_CLEAR.add(Material.matchMaterial("hbm:niter")),
        ITEMS_TO_CLEAR.add(Material.matchMaterial("hbm:fluorite")),
        ITEMS_TO_CLEAR.add(Material.matchMaterial("hbm:lithium")),
        // Ajoute le restant de tes items
    }

    private void scheduleClearTask() {
        new BukkitRunnable() {
            @Override
            public void run() {
                announceClear(10, "world");
            }
        }.runTaskTimer(this, 0, 2400);
    }

    private void announceClear(int secondsBefore, String worldName) {
        World world = Bukkit.getWorld(worldName);
        if (world == null) return;

        new BukkitRunnable() {
            int countdown = secondsBefore;
            @Override
            public void run() {
                if (countdown == 0) {
                    sendMessageToWorld(world, "§8→ §7Clearing Items ...");
                    clearItemsInWorld(world);
                    cancel();
                    return;
                }
                countdown--;
            }
        }.runTaskTimer(this, 0, 20);
    }

    private void sendMessageToWorld(World world, String message) {
        for (Player player : world.getPlayers()) {
            player.spigot().sendMessage(ChatMessageType.ACTION_BAR, new TextComponent(message));
        }
    }

    private void clearItemsInWorld(World world) {
        for (Entity entity : world.getEntities()) {
            if (entity instanceof Item) {
                Item item = (Item) entity;
                if (ITEMS_TO_CLEAR.contains(item.getItemStack().getType())) {
                    item.remove();
                }
            }
        }
    }
}
```
Bon bon bon pour les explications voilà : 

- Dans un premier temps, on utilisera un Set pour les items pour avoir une recherche plus rapide. Sans rentrer dans les détails, l'utilisation d'un Set fait passer la complexité de l'algo à **O(1)** au lieu de **O(n)** [Voilà le lien Wikipédia si tu ne sais pas ce qu'est la complexité d'un algo](https://fr.wikipedia.org/wiki/Analyse_de_la_complexit%C3%A9_des_algorithmes)

- Ensuite, pour une question de maintenabilité de code / lisibilité, on crée une méthode séparée `initItemsToClear()`

- En ce qui concerne les constantes, on peut utiliser `static final` pour LOGO et ITEMS_TO_CLEAR pour la lisibilité et les perfs

- Pour la méthode `clearItemsInWorld()` pourquoi ne pas passer directement par l'objet `World` au lieu du nom ?? C'est débile de faire une recherche supplémentaire ??

- Pour finir, on nettoie les imports inutiles pour la lisibilité et la cohérence.

Enfin bref, voilà une version optimisée d'après ma lecture rapide. Il doit sans doute y avoir autre chose mais c'était le plus flagrant.

PS : Apparemment, ce plugin est " Smart Clear lag, 90% smarter than OpenWar Player's". Du coup maintenant avec ces optimisations, le plugin sera également plus smart que le dev initial btw

PS2 : Je n'ai pas testé en compilant mais je suis certain que ça fonctionne.

**Comment by Charpyy** [comment]
👍 je m'amuserais à ça quand j'aurais le temps, là j'ai un serveur à dev, Merci.

ps: m'attaquer sur un code qui est rendu publique dans l'unique but de présenter ce que j'ai été capable de faire pendant 3 mois, de java en partant de zéro, c'est très petit quand on sait que toi et les membres de ta faction n'ont même pas compris le principe du serveur.
